"""empty message

Revision ID: 6f66ad6e8e62
Revises: a034094cf0c2
Create Date: 2019-04-15 00:40:13.181005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f66ad6e8e62'
down_revision = 'a034094cf0c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('answer', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'answer')
    # ### end Alembic commands ###
